services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    volumes:
      - ./api/brobot:/app/brobot
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - MODEL_NAME=${MODEL_NAME}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${BROBOT_DATABASE_USER}
      POSTGRES_PASSWORD: ${BROBOT_DATABASE_PASSWORD}
      POSTGRES_DB: ${BROBOT_DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: