# .github/workflows/ci.yml
name: Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Integration Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v4

      # https://docs.astral.sh/uv/guides/integration/github/#installation
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.14"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
    
      - name: Install project dependencies
        run: uv sync --all-extras --dev

      - name: Install project in editable mode
        run: uv pip install -e .

      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest tests